[program:ltx-suite]
command=/bin/bash /opt/ltx-suite/docker/start.sh
autostart=true
autorestart=unexpected
exitcodes=0
startsecs=0
startretries=3
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/portal/ltx-supervisor.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
redirect_stderr=true
priority=999
